[env]
exp_dir = 'experiments'
exp_name = 'L3F_split20_8x8'
num_workers = 8

[net]
resolution = 8

[train]
num_iters = 180000
batch_size = 1
base_lr = 1e-4
save_step = 20000

[train.dataset]
root = './L3F-dataset'
split = '20'
patch_size = 180
view_size = 12
cropped_resolution = 8

[val]
val_step = 20000

[val.dataset]
root = './L3F-dataset'
split = '20'
cropped_resolution = 8

[[val.metrics]]
name = 'PSNR'
primary = true

[[val.metrics]]
name = 'SSIM'

[test]

[test.dataset]
root = './L3F-dataset'
split = '20'
cropped_resolution = 8

[[test.metrics]]
name = 'PSNR'

[[test.metrics]]
name = 'SSIM'
